In [1]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from io import StringIO

# Load the data
data_text = """Primer	Bullet	COL	Powder	Weight	Count	Loaded/Shot	FPS Avg	FPS ES	FPS SD	Group Size	Group	Day Group
ELDX	ELDX175	3.29	ELDX		5	7/15/24				1.70	1	1
ELDX	ELDX175	3.29	ELDX		5	7/15/24				1.15	2	2
Match	Match180	3.29	Match		5	7/15/24				2.25	3	3
Match	Match180	3.29	Match		3	3/23/24				2.16	4	1
Match	Match180	3.29	Match		3	3/23/24				1.18	5	2
Match	Match180	3.29	Match		3	3/23/24				1.32	6	3
Match	Match180	3.29	Match		5	2/26/24				2.60	7	1
Match	Match180	3.29	Match		5	2/26/24				2.40	8	2
Match	Match180	3.29	Match		5	2/26/24				3.20	9	3
ELDX	ELDX175	3.29	ELDX		5	2/25/24				3.40	10	4
Outfitter	Outfitter		Outfitter		5	2/25/24				3.50	11	5
Ascent	Ascent		Ascent		5	2/25/24				3.30	12	6
ELDX	ELDX175	3.29	ELDX		5	7/15/24	2854	28.0	12.0	2.00	13	1
ELDX	ELDX175	3.29	ELDX		5	7/15/24	2904	45.0	25.0	2.00	14	2
Remington 9 1/2 M	ELDX175	3.30	H1000	65.0	5	8/6/24	2788	45.0	22.6	1.20	15	1
Remington 9 1/2 M	ELDX175	3.30	H1000	66.0	5	8/6/24	2891	39.0	13.0	1.20	16	2
Remington 9 1/2 M	ELDX175	3.30	H1000	67.0	5	8/6/24	2842	59.0	23.4	2.20	17	3
Remington 9 1/2 M	ELDX175	3.30	RL23	59.0	5	8/6/24	2706	19.0	7.5	1.50	18	4
Remington 9 1/2 M	ELDX175	3.30	RL23	60.0	5	8/6/24	2764	17.0	6.3	1.40	19	5
Remington 9 1/2 M	ELDX175	3.30	RL23	61.0	5	8/6/24	2784	6.0	2.2	1.20	20	6
Remington 9 1/2 M	ELDX175	3.30	IMR7828	62.0	5	8/6/24	2763	14.0	6.1	2.20	21	7
Remington 9 1/2 M	ELDX175	3.30	IMR7828	63.0	5	8/6/24	2813	39.0	13.8	2.50	22	8
Remington 9 1/2 M	ELDX175	3.30	IMR7828	64.0	5	8/6/24	2857	16.0	6.1	1.70	23	9
Remington 9 1/2 M	ELDX175	3.32	H1000	65.0	5	8/8/24	2778	34.0	11.4	1.30	24	1
Remington 9 1/2 M	ELDX175	3.32	H1000	66.0	5	8/8/24	2851	18.0	8.0	1.60	25	2
Remington 9 1/2 M	ELDX175	3.32	H1000	67.0	5	8/8/24	2866	30.0	12.1	1.20	26	3
Remington 9 1/2 M	ELDX175	3.32	RL23	59.5	5	8/8/24	2736	32.0	13.1	0.60	27	4
Remington 9 1/2 M	ELDX175	3.32	RL23	60.0	5	8/9/24	2755	26.0	9.6	1.20	28	5
Remington 9 1/2 M	ELDX175	3.32	RL23	60.5	5	8/9/24	2778	27.0	9.9	1.00	29	6
Remington 9 1/2 M	ELDX175	3.32	RL23	61.0	5	8/9/24	2802	11.0	4.4	0.90	30	7
Remington 9 1/2 M	ELDX175	3.32	RL23	61.0	10	8/9/24					31	
Remington 9 1/2 M	ELDX175	3.32	RL23	59.5	5	8/9/24	2730	19.7	7.4	1.80	32	1
Remington 9 1/2 M	ELDX175	3.32	RL23	60.0	5	8/9/24	2748	15.4	5.4	1.35	33	2
Remington 9 1/2 M	ELDX175	3.32	RL23	60.5	5	8/9/24	2773	14.2	6.2	1.25	34	3
Remington 9 1/2 M	ELDX175	3.32	RL23	61.0	5	8/9/24					35	4
Remington 9 1/2 M	ELDX175	3.34	RL23	59.5	5	8/9/24	2729	11.4	4.2	1.37	36	5
Remington 9 1/2 M	ELDX175	3.32	RL23	61.0	35	6/15/25					37	
Remington 9 1/2 M	ELDX175	3.32	N560	60.0	5	6/25/25	2689	16.1	5.7	0.75	38	1
Remington 9 1/2 M	ELDX175	3.32	N560	62.0	5	6/25/25	2770	14.1	5.1	1.25	39	2
Remington 9 1/2 M	ELDX175	3.32	N560	64.0	5	6/25/25	2848	17.6	5.6	1.40	40	3
Remington 9 1/2 M	ELDX175	3.32	H4831	58.0	5	6/25/25	2598	16.2	5.2	0.80	41	4
Remington 9 1/2 M	ELDX175	3.32	H4831	60.0	5	6/25/25	2681	16.7	7.0	1.20	42	5
Remington 9 1/2 M	ELDX175	3.32	H4831	62.0	5	6/25/25	2754	33.6	13.1	1.80	43	6
Remington 9 1/2 M	ELDX175	3.32	Retumbo	64.0	5	6/25/25	2646	25.4	9.5	1.70	44	7
Remington 9 1/2 M	ELDX175	3.32	Retumbo	66.0	5	6/25/25	2729	13.0	5.8	1.75	45	8
Remington 9 1/2 M	ELDX175	3.32	Retumbo	68.0	5	6/25/25	2817	29.1	10.4	1.50	46	9
Remington 9 1/2 M	ELDX175	3.32	N560	59.0	5	7/4/25	2654	39.9	14.9	0.85	47	1
Remington 9 1/2 M	ELDX175	3.32	N560	61.0	5	7/4/25	2746	15.8	6.0	1.70	48	3
Remington 9 1/2 M	ELDX175	3.32	H4831	56.0	5	7/4/25	2527	20.2	8.3	1.10	49	5
Remington 9 1/2 M	ELDX175	3.32	H4831	57.0	5	7/4/25	2564	20.1	7.9	1.26	50	6
Remington 9 1/2 M	ELDX175	3.32	H4831	58.0	5	7/4/25	2598	20.3	6.6	0.70	51	7
Remington 9 1/2 M	ELDX175	3.32	H4831	59.0	5	7/4/25	2651	33.1	14.2	1.37	52	8
Remington 9 1/2 M	ELDX175	3.32	N560	59.0	5	7/5/25	2634	36.5	11.8	1.70	53	1
Remington 9 1/2 M	ELDX175	3.32	N560	59.5	5	7/5/25	2675	18.5	6.8	1.13	54	2
Remington 9 1/2 M	ELDX175	3.32	N560	60.0	5	7/5/25	2690	11.4	4.2	1.80	55	3
Remington 9 1/2 M	ELDX175	3.32	H4831	57.5	5	7/5/25	2576	20.8	7.0	0.70	56	4
Remington 9 1/2 M	ELDX175	3.32	H4831	58.0	5	7/5/25	2601	23.4	8.6	1.40	57	5
Remington 9 1/2 M	ELDX175	3.32	H4831	58.5	5	7/5/25	2618	34.7	11.4	1.50	58	6
Remington 9 1/2 M	ELDX175	3.40	H1000	65.0	5	7/14/25	2793	49.7	17.3	1.13	59	1
Remington 9 1/2 M	ELDX175	3.40	H1000	65.5	5	7/14/25	2817	36.3	14.4	2.00	60	2
Remington 9 1/2 M	ELDX175	3.40	H1000	66.0	5	7/14/25	2848	20.8	6.8	1.70	61	3
Remington 9 1/2 M	ELDX175	3.40	H1000	66.5	5	7/14/25	2864	18.0	6.4	2.20	62	4
Remington 9 1/2 M	ELDX175	3.40	H1000	67.0	5	7/14/25	2894	30.8	11.6	2.20	63	5
Remington 9 1/2 M	ELDX175	3.40	H4831	58.0	5	7/14/25	2621	43.5	15.7	1.90	64	6
Remington 9 1/2 M	ELDX175	3.40	H4831	59.0	5	7/14/25	2664	16.0	5.2	1.15	65	7
Remington 9 1/2 M	ELDX175	3.40	H4831	60.0	5	7/14/25	2710	30.7	12.6	1.90	66	8
Remington 9 1/2 M	ELDX175	3.40	H4831	61.0	5	7/14/25	2742	12.8	5.3	1.40	67	9
Remington 9 1/2 M	ELDX175	3.40	H4831	62.0	5	7/14/25	2786	15.5	5.1	1.50	68	10"""

df = pd.read_csv(StringIO(data_text), sep='\t')

# Clean up data types
df['FPS Avg'] = pd.to_numeric(df['FPS Avg'], errors='coerce')
df['FPS SD'] = pd.to_numeric(df['FPS SD'], errors='coerce')
df['Group Size'] = pd.to_numeric(df['Group Size'], errors='coerce')
df['Weight'] = pd.to_numeric(df['Weight'], errors='coerce')

c:\Users\ken\AppData\Local\Programs\Python\Python313\python.exe

In [2]:
# Show which loads had smallest group size
top_groups = df.sort_values('Group Size').head(10)[['Powder', 'Weight', 'COL', 'FPS Avg', 'FPS SD', 'Group Size']]
print("Top 10 Smallest Groups")
display(top_groups)  # or just top_groups

Top 10 Smallest Groups

   Powder  Weight   COL  FPS Avg  FPS SD  Group Size
26   RL23    59.5  3.32   2736.0    13.1        0.60
50  H4831    58.0  3.32   2598.0     6.6        0.70
55  H4831    57.5  3.32   2576.0     7.0        0.70
37   N560    60.0  3.32   2689.0     5.7        0.75
40  H4831    58.0  3.32   2598.0     5.2        0.80
46   N560    59.0  3.32   2654.0    14.9        0.85
29   RL23    61.0  3.32   2802.0     4.4        0.90
28   RL23    60.5  3.32   2778.0     9.9        1.00
48  H4831    56.0  3.32   2527.0     8.3        1.10
53   N560    59.5  3.32   2675.0     6.8        1.13

In [3]:
# Average group size by powder and weight, with count, top 10 only
powder_weight_stats = (
    df.groupby(['Powder', 'Weight'])
    .agg(
        mean_group_size=('Group Size', 'mean'),
        mean_fps=('FPS Avg', 'mean'),
        count=('Group Size', 'count')
    )
    .reset_index()
    .sort_values('mean_group_size')
    .head(10)
)

print("Top 10 Powder/Weight Combinations by Average Group Size (with mean FPS and count):")
display(powder_weight_stats)

Top 10 Powder/Weight Combinations by Average Group Size (with mean FPS and count):

   Powder  Weight  mean_group_size     mean_fps  count
7   H4831    57.5         0.700000  2576.000000      1
27   RL23    61.0         1.050000  2793.000000      2
5   H4831    56.0         1.100000  2527.000000      1
26   RL23    60.5         1.125000  2775.500000      2
18   N560    59.5         1.130000  2675.000000      1
8   H4831    58.0         1.200000  2604.500000      4
0   H1000    65.0         1.210000  2786.333333      3
21   N560    62.0         1.250000  2770.000000      1
24   RL23    59.5         1.256667  2731.666667      3
10  H4831    59.0         1.260000  2657.500000      2

In [4]:
# Compute correlation with Group Size
corr_columns = ['FPS Avg', 'FPS ES', 'FPS SD', 'Group', 'Day Group', 'Group Size']
corr_df = df[corr_columns].corr()

print("Correlation Matrix (Group Size and related columns):")
display(corr_df['Group Size'].sort_values(ascending=False))  # Shows correlation with Group Size

Correlation Matrix (Group Size and related columns):

Group Size    1.000000
FPS Avg       0.423863
FPS SD        0.263288
FPS ES        0.237113
Day Group     0.013551
Group        -0.327411
Name: Group Size, dtype: float64

In [5]:
# Basic stats
group_stats = df.groupby('Powder')[['FPS Avg', 'FPS ES', 'FPS SD', 'Group Size']].agg(['mean', 'count']).dropna()

# Sort by mean group size (ascending)
group_stats = group_stats.sort_values(('Group Size', 'mean'))

print("Powder Performance Summary (sorted by mean group size)")
display(group_stats)

Powder Performance Summary (sorted by mean group size)

             FPS Avg           FPS ES           FPS SD       Group Size
                mean count       mean count       mean count       mean count
Powder
RL23     2755.000000    11  18.063636    11   6.927273    11   1.233636    11
H4831    2646.066667    15  23.840000    15   8.880000    15   1.312000    15
N560     2713.250000     8  21.237500     8   7.512500     8   1.322500     8
H1000    2839.272727    11  34.600000    11  13.363636    11   1.630000    11
Retumbo  2730.666667     3  22.500000     3   8.566667     3   1.650000     3
ELDX     2879.000000     2  36.500000     2  18.500000     2   2.050000     5
IMR7828  2811.000000     3  23.000000     3   8.666667     3   2.133333     3